# Generated by Django 4.2.7 on 2023-12-08 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_alter_team_captain_id_alter_team_count_members_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='avatar',
            field=models.ImageField(blank=True, default='teams_avatars/avatarTeams.png', null=True, upload_to='teams_avatars/%Y/%m/%d'),
        ),
    ]
