# Generated by Django 4.2.7 on 2023-12-16 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_alter_team_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='detailed_description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
