# Generated by Django 4.2.7 on 2023-12-16 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_team_detailed_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='telegram_team',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='detailed_description',
            field=models.TextField(null=True),
        ),
    ]
