# Generated by Django 4.2.7 on 2023-11-30 11:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Аноним', max_length=20)),
                ('surname', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[('male', 'Мужчина'), ('female', 'Женщина')], max_length=10)),
                ('sport_type', models.CharField(choices=[('ski', 'Лыжи'), ('run', 'Бег')], max_length=10)),
                ('characteristics', models.TextField()),
                ('inventory', models.TextField()),
                ('athlete_photo', models.ImageField(blank=True, null=True, upload_to='athlete_photos/%Y/%m/%d')),
                ('inventory_photo', models.ImageField(blank=True, null=True, upload_to='inventory_photos/%Y/%m/%d')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
