# Generated by Django 4.2.7 on 2023-12-15 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('athlete_profile', '0002_profile_city_profile_contacts_messenger_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='inventory',
        ),
    ]
