# Generated by Django 4.2.7 on 2023-12-15 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('athlete_profile', '0003_remove_profile_inventory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='inventory_photo',
        ),
        migrations.CreateModel(
            name='ProfilePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='inventory_photos/%Y/%m/%d')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_photos', to='athlete_profile.profile')),
            ],
        ),
    ]
