# Generated by Django 4.2.7 on 2023-12-17 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athlete_profile', '0004_remove_profile_inventory_photo_profilephoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='athlete_photo',
            field=models.ImageField(blank=True, default='athlete_photos/defaultProfile.jpg', null=True, upload_to='athlete_photos/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('male', 'Мужчина'), ('female', 'Женщина')], default=('male', 'Мужчина'), max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sport_type',
            field=models.CharField(choices=[('ski', 'Лыжи'), ('run', 'Бег')], default=('ski', 'Лыжи'), max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='surname',
            field=models.CharField(default='Аноним', max_length=20),
        ),
    ]
