# Generated by Django 4.2.7 on 2023-12-27 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athlete_profile', '0005_alter_profile_athlete_photo_alter_profile_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('male', 'Мужчина'), ('female', 'Женщина')], default='male', max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sport_type',
            field=models.CharField(choices=[('ski', 'Лыжи'), ('run', 'Бег')], default='ski', max_length=10),
        ),
    ]
