# Generated by Django 4.2.7 on 2023-12-31 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='distance',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='workout',
            name='duration',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='workout',
            name='pace',
            field=models.CharField(max_length=20),
        ),
    ]
